/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../platform-electron/src/electron_app';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '../../../../platform-electron/src/app/electron_app_renderer';
import * as import6 from '@angular/core/src/application_init';
import * as import7 from '@angular/core/src/application_ref';
import * as import8 from '@angular/core/src/linker/compiler';
import * as import9 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import10 from '@angular/core/src/animation/animation_queue';
import * as import11 from '@angular/core/src/linker/view_utils';
import * as import12 from '@angular/core/src/di/injector';
import * as import13 from '@angular/core/src/i18n/tokens';
import * as import14 from '@angular/core/src/application_tokens';
import * as import15 from '@angular/core/src/zone/ng_zone';
import * as import16 from '@angular/core/src/console';
import * as import17 from '@angular/core/src/testability/testability';
import * as import18 from '@angular/core/src/error_handler';
import * as import19 from '@angular/core/src/render/api';
import * as import20 from '@angular/core/src/security';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import22 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class ElectronAppModuleInjector extends import0.NgModuleInjector<import1.ElectronAppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _ElectronAppModule_2:import1.ElectronAppModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  _ErrorHandler_5:any;
  _RootRenderer_6:import5.ElectronRootRenderer;
  _APP_INITIALIZER_7:any[];
  _ApplicationInitStatus_8:import6.ApplicationInitStatus;
  _ApplicationRef__9:import7.ApplicationRef_;
  __ApplicationRef_10:any;
  __Compiler_11:import8.Compiler;
  __APP_ID_12:any;
  __DomSanitizer_13:import9.DomSanitizerImpl;
  __Sanitizer_14:any;
  __AnimationQueue_15:import10.AnimationQueue;
  __ViewUtils_16:import11.ViewUtils;
  __IterableDiffers_17:any;
  __KeyValueDiffers_18:any;
  constructor(parent:import12.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == null)) { (this.__LOCALE_ID_3 = import3._localeFactory(this.parent.get(import13.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _ApplicationRef_10():any {
    if ((this.__ApplicationRef_10 == null)) { (this.__ApplicationRef_10 = this._ApplicationRef__9); }
    return this.__ApplicationRef_10;
  }
  get _Compiler_11():import8.Compiler {
    if ((this.__Compiler_11 == null)) { (this.__Compiler_11 = new import8.Compiler()); }
    return this.__Compiler_11;
  }
  get _APP_ID_12():any {
    if ((this.__APP_ID_12 == null)) { (this.__APP_ID_12 = import14._appIdRandomProviderFactory()); }
    return this.__APP_ID_12;
  }
  get _DomSanitizer_13():import9.DomSanitizerImpl {
    if ((this.__DomSanitizer_13 == null)) { (this.__DomSanitizer_13 = new import9.DomSanitizerImpl()); }
    return this.__DomSanitizer_13;
  }
  get _Sanitizer_14():any {
    if ((this.__Sanitizer_14 == null)) { (this.__Sanitizer_14 = this._DomSanitizer_13); }
    return this.__Sanitizer_14;
  }
  get _AnimationQueue_15():import10.AnimationQueue {
    if ((this.__AnimationQueue_15 == null)) { (this.__AnimationQueue_15 = new import10.AnimationQueue(this.parent.get(import15.NgZone))); }
    return this.__AnimationQueue_15;
  }
  get _ViewUtils_16():import11.ViewUtils {
    if ((this.__ViewUtils_16 == null)) { (this.__ViewUtils_16 = new import11.ViewUtils(this._RootRenderer_6,this._Sanitizer_14,this._AnimationQueue_15)); }
    return this.__ViewUtils_16;
  }
  get _IterableDiffers_17():any {
    if ((this.__IterableDiffers_17 == null)) { (this.__IterableDiffers_17 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_17;
  }
  get _KeyValueDiffers_18():any {
    if ((this.__KeyValueDiffers_18 == null)) { (this.__KeyValueDiffers_18 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_18;
  }
  createInternal():import1.ElectronAppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._ElectronAppModule_2 = new import1.ElectronAppModule();
    this._ErrorHandler_5 = import1.errorHandler();
    this._RootRenderer_6 = new import5.ElectronRootRenderer();
    this._APP_INITIALIZER_7 = [
      import1.setUpRenderFlushing(this.parent.get(import15.NgZone),this._RootRenderer_6),
      import1.setupElectronApp
    ]
    ;
    this._ApplicationInitStatus_8 = new import6.ApplicationInitStatus(this._APP_INITIALIZER_7);
    this._ApplicationRef__9 = new import7.ApplicationRef_(this.parent.get(import15.NgZone),this.parent.get(import16.Console),this,this._ErrorHandler_5,this,this._ApplicationInitStatus_8,this.parent.get(import17.TestabilityRegistry,(null as any)),this.parent.get(import17.Testability,(null as any)));
    return this._ElectronAppModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import1.ElectronAppModule)) { return this._ElectronAppModule_2; }
    if ((token === import13.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import18.ErrorHandler)) { return this._ErrorHandler_5; }
    if ((token === import19.RootRenderer)) { return this._RootRenderer_6; }
    if ((token === import6.APP_INITIALIZER)) { return this._APP_INITIALIZER_7; }
    if ((token === import6.ApplicationInitStatus)) { return this._ApplicationInitStatus_8; }
    if ((token === import7.ApplicationRef_)) { return this._ApplicationRef__9; }
    if ((token === import7.ApplicationRef)) { return this._ApplicationRef_10; }
    if ((token === import8.Compiler)) { return this._Compiler_11; }
    if ((token === import14.APP_ID)) { return this._APP_ID_12; }
    if ((token === import9.DomSanitizer)) { return this._DomSanitizer_13; }
    if ((token === import20.Sanitizer)) { return this._Sanitizer_14; }
    if ((token === import10.AnimationQueue)) { return this._AnimationQueue_15; }
    if ((token === import11.ViewUtils)) { return this._ViewUtils_16; }
    if ((token === import21.IterableDiffers)) { return this._IterableDiffers_17; }
    if ((token === import22.KeyValueDiffers)) { return this._KeyValueDiffers_18; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__9.ngOnDestroy();
  }
}
export const ElectronAppModuleNgFactory:import0.NgModuleFactory<import1.ElectronAppModule> = new import0.NgModuleFactory<any>(ElectronAppModuleInjector,import1.ElectronAppModule);